from datetime import datetime

def format_news_html_pro(data, thought):
    date = datetime.now().strftime("%d %B %Y")

    html = f"""
    <html>
    <body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial, sans-serif;">
      <div style="max-width:600px;margin:auto;background:#ffffff;border-radius:12px;overflow:hidden;">

        <!-- HEADER -->
        <div style="background:#0f172a;color:white;padding:20px;text-align:center;">
          <h1 style="margin:0;font-size:22px;">🧠 AI Daily Digest</h1>
          <p style="margin:5px 0 0 0;font-size:12px;color:#cbd5f5;">{date}</p>
        </div>

        <!-- THOUGHT -->
        <div style="background:#fff3cd;padding:15px;margin:15px;border-radius:10px;">
          <h3 style="margin:0 0 5px 0;">💡 Thought of the Day</h3>
          <p style="margin:0;font-size:14px;">{thought}</p>
        </div>
    """

    if not data:
        html += "<p style='padding:20px;'>No news available today</p>"
    else:
        for i, n in enumerate(data, 1):
            html += f"""
            <!-- CARD -->
            <div style="margin:15px;border:1px solid #e5e7eb;border-radius:10px;padding:15px;background:#fafafa;">
                
                <h3 style="margin:0 0 8px 0;color:#111827;">
                    🔥 {i}. {n.get("title","").upper()}
                </h3>

                <p style="margin:0 0 6px 0;font-size:12px;color:#6b7280;">
                    📊 {n.get("score",0)}/10 | 🏷️ {n.get("category","General")}
                </p>

                <p style="margin:10px 0;font-size:14px;color:#374151;">
                    👉 {n.get("content","")}
                </p>

                <a href="{n.get("link","#")}" 
                   style="display:inline-block;margin-top:8px;padding:8px 12px;
                   background:#2563eb;color:white;text-decoration:none;
                   border-radius:6px;font-size:12px;">
                   🔗 Read More
                </a>

                <p style="margin-top:8px;font-size:11px;color:#9ca3af;">
                    Source: {n.get("source","")}
                </p>

            </div>
            """

    html += """
        <!-- FOOTER -->
        <div style="text-align:center;padding:15px;font-size:11px;color:#9ca3af;">
            🚀 Stay updated. Stay ahead.<br>
            🤖 Generated by AI Bot
        </div>

      </div>
    </body>
    </html>
    """

    return html